name: Bug
description: Something isn't working
title: '[BUG] <title>'
labels: ['bug']
assignees:
  - hywax

body:
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you running Mafl?
      options:
        - Self-Hosted (Docker)
        - Self-Hosted (Node)
        - Cloud Service (Static)
        - Other (Specify below)
    validations:
      required: true

  - type: input
    id: system
    attributes:
      label: System
      description: >-
        For deployment issues, specify your [distro or OS](https://whatsmyos.com/) and/ or Docker version.
        For client-side issues, include your [browser version](https://www.whatsmybrowser.org/)
      placeholder: e.g. Firefox 101, Manjaro Linux 21.3.0, Docker 20.10.16
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Mafl are you running?
      placeholder: 1.3.0 ← should look like this (check config menu)
    validations:
      required: false

  - type: textarea
    id: reproduce
    attributes:
      label: Describe the problem
      description: Please describe exactly what is not working, include the steps to reproduce, actual result and expected result
      placeholder: When doing ABC then DEF, I expect to see XYZ, but I actually see ZYX
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Additional info
      description: Logs? Screenshots? Yes, please.
      placeholder: If the issue happens during build-time, include terminal logs. For run-time errors, include browser logs which you can view in the Dev Tools (F12), under the Console tab. Take care to blank out any personal info.
    validations:
      required: false
