name: 🐞 Bug report
description: Create a bug report for this project
labels: [bug, pending]
body:
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you running Mafl?
      options:
        - Self-Hosted (Docker)
        - Self-Hosted (Node)
        - Other (Specify below)
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Mafl are you running?
      placeholder: 1.3.0 ← should look like this (check the footer of app)
    validations:
      required: false
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: additonal
    attributes:
      label: Additional context
      description: If applicable, add any other context about the problem here
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Optional if provided reproduction. Please try not to insert an image but copy paste the log text.
      render: shell-script
