name: Feature Request
description: Suggest an idea for future development
title: '[FEATURE_REQUEST] <title>'
labels: ['feature request']

body:
  - type: textarea
    id: issue
    attributes:
      label: Is your feature request related to a problem? If so, please describe.
      description:
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      placeholder: An outline of how you would like this to be implemented, include as much details as possible
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is the development of this feature
      options:
        - Low (Nice-to-have)
        - Medium (Would be very useful)
        - High (The app does not function without it)
    validations:
      required: true

  - type: dropdown
    id: canImplement
    attributes:
      label: Is this something you would be keen to implement
      description: Are you raising this ticket in order to get an issue number for your PR?
      options:
        - 'No'
        - 'Maybe'
        - 'Yes!'
    validations:
      required: false
