/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoostyLink: typeof import('./theme/components/BoostyLink.vue')['default']
    GithubLink: typeof import('./theme/components/GithubLink.vue')['default']
    PreviewImage: typeof import('./theme/components/PreviewImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sponsor: typeof import('./theme/components/Sponsor.vue')['default']
  }
}
