name: CI

on:
  push:
    paths-ignore:
      - "apps/docs/**"
      - ".md"
    branches:
      - main
  pull_request:
    paths-ignore:
      - "apps/docs/**"
      - "*.md"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        with:
          version: 9.14.2
          run_install: true

      - name: ESLint
        run: pnpm run lint

      - name: Types
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build
